### ISSUE TITLE
Pre-trained weights for fully supervised setting

### ISSUE THREAD

**Issue by reneeish** [Susmit-A/FSHDR#1]
Thanks for the nice work.

You mentioned that the BridgeNet model weights for each of zero-shot, one-shot, and five-shot setting are provided. Could you also provide the model weights for fully supervised setting which is included in your paper?

**Comment by Susmit-A** [comment]
Hi,

Thank you for your interest in our work!

We have uploaded weights for the fully supervised model in the `results` folder.
