### ISSUE TITLE
Prabhakar dataset (ICCP19)

### ISSUE THREAD

**Issue by reneeish** [Susmit-A/FSHDR#2]
Hello, I have a question about Prabhakar dataset (ICCP19).
I've downloaded Prabhakar dataset from the link you provided,
but there were several sets without ground truth HDR image and some of the directories were not aligned. (GT file or txt file exists in different folders in each set.)
I wonder if you could check the dataset.
(I'm writing here since I couldn't find the github for your ICCP19 paper.)
Thank you!

**Comment by Susmit-A** [comment]
Thank you for your interest in our work!

We have provided a script to prepare and structure the downloaded ICCP19 dataset in the "dataset" folder. Please refer to the "Dataset Preparation" section of the README for instructions on preparing the downloaded dataset using the script.

**Comment by LiuzhuForFun** [comment]
Hi, the link of  Prabhakar dataset is not valid. Could you please to provide a new web link to download ?

**Comment by Susmit-A** [comment]
Updated the link in the README.
