### ISSUE TITLE
Input size of experiments 

### ISSUE THREAD

**Issue by fonte-fs** [Susmit-A/FSHDR#3]
Dear，

Thanks for your sharing of your nice work. Here I have some questions.

As for your work, you mentioned in your paper that patch size is 64x64 and the patch size of Yan's work (Attention-guided network in 2019)  is 256x256.  What‘s more, the patch size of  other works may be not same as yours.  How do you ensure that your work uses the same amount of  labeled data as other work ?

Maybe I didn't express it very clearly. Looking forward to your reply. Thanks.

**Comment by Susmit-A** [comment]
Hi,

Thank you for your interest in our work!
The amount of "labeled data" for training is the same across all works - for example, 74 sequences in the Kalantari17 dataset,  with their ground truths. What differs is the way that data is used. 

Using 64x64 patches does not change the amount of data available for training. It is just a choice we made that minimized training times while maximizing performance.

**Comment by fonte-fs** [comment]
So "5-shot" means that  you use 5 sequences for training your network and others's work, no matter how many or how large patches (generated from sequences)  you use for training for all works. Am I right？ 

I'm interested in the setup of few-show related works.

**Comment by Susmit-A** [comment]
Yes, that is correct.

**Comment by fonte-fs** [comment]
Did you use all  generated patches in experiments (both your network and others' networks) ?

**Comment by Susmit-A** [comment]
The patches were randomly sampled in our work. The exact details about training procedures can be found in the paper.

**Comment by fonte-fs** [comment]
Thanks for your reply.  Now I understand.

Can your share your supplementary material mentioned in few-shot HDR video part of your paper? I can't find it in CVPR website.
