### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by weiyeeah** [Susmit-A/FSHDR#6]
Thanks

**Comment by GuitarZH** [comment]
I also find this image_type problem, it's confusing for me to align inputs in testing inference. @Susmit-A @KRamPrabhakar can you help me? What should I do to use "flow_corrected"?

**Comment by Susmit-A** [comment]
Hi, thank you for your interest in our work!

The line `image_type == 'flow_corrected'` means that the images that have been aligned to the medium exposure image using optical flow will be used for valuation. The validation sequences can be flow corrected by following the instructions in the README.

**Comment by GuitarZH** [comment]
> 

Thanks for your reply. In addition, should I also use the "flow_corrected" images in the training phase? Because I find it is also used in sample_bash_scripts/train_S1.sh.

**Comment by Susmit-A** [comment]
Yes, flow correction is performed during training as well.

**Comment by weiyeeah** [comment]
Thanks a lot.

Does it mean we should use **flow_corrected** images(which are aligned to the medium exposure image) as dynamic inputs in training stage1?
